["CI/CD"]
color = "72db98"
name = "CI/CD"
description = "This involves the CI/CD process (Github Actions, PyPi, ReadTheDocs, etc.)"

[blocked]
color = "000000"
name = "blocked"
description = "This issue or pull request is blocked for now. We'd reconsider it in the future."

[bug]
color = "d73a4a"
name = "bug"
description = "Something isn't working"

[design]
color = "8acc3b"
name = "design"
description = "This involves redesigning or design questions."

[documentation]
color = "0075ca"
name = "documentation"
description = "Improvements or additions to documentation"

[duplicate]
color = "cfd3d7"
name = "duplicate"
description = "This issue or pull request already exists"

[enhancement]
color = "a2eeef"
name = "enhancement"
description = "New feature or request"

["good first issue"]
color = "7057ff"
name = "good first issue"
description = "Good for newcomers"

["help wanted"]
color = "008672"
name = "help wanted"
description = "Extra attention is needed"

[invalid]
color = "e4e669"
name = "invalid"
description = "This doesn't seem right"

[quality]
color = "f98943"
name = "quality"
description = "Code quality related (static code analysis, code coverage, etc.)"

[question]
color = "d876e3"
name = "question"
description = "Further information is requested"

[testing]
color = "fbca04"
name = "testing"
description = "Testing related (unit tests, system tests, integration tests, etc.)"

[wontfix]
color = "ffffff"
name = "wontfix"
description = "This will not be worked on because it violates design choices or out of scope"

["work in progress"]
color = "c2e0c6"
name = "work in progress"
description = "This is something that takes time and patience. We're working on it!"
